/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.DAO_ChuyenTau;
import Database.ConnectDatabase;
import Entity.LichTrinhTau;
import Entity.Tau;
import Entity.TuyenTau;

import java.awt.*;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author ASUS
 */
public class ChuyenTau extends javax.swing.JFrame {

    /**
     * Creates new form ChuyenTau
     */
    public ChuyenTau() {

        initComponents();
        //combobox
        AutoCompleteDecorator.decorate(cbb_Tau);
        ConnectDatabase.getInstance().connect();
        fillComboBoxTau();
        fillComboBoxTuyenTau(); 
        fillComboBoxTrangThai();
        DAO_ChuyenTau dao = new DAO_ChuyenTau();
        dao.capNhatTrangThaiTau();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnGroupTrangThai = new javax.swing.ButtonGroup();
        btnGrTuyen = new javax.swing.ButtonGroup();
        btnGrTau = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        timePicker1 = new com.raven.swing.TimePicker();
        btnGrTanSuat = new javax.swing.ButtonGroup();
        jPanel_Main = new javax.swing.JPanel();
        gruopForm = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnTimTheoMa = new javax.swing.JButton();
        txtMaLichTrinh = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        groupBtn = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        groupText = new javax.swing.JPanel();
        groupText1 = new javax.swing.JPanel();
        txtMa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbb_Tau = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbbTrangThai = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jDateChooserNgayDi = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtGioDi = new javax.swing.JTextField();
        jButtonGioDi = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jPanel_Loc = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jDateChooserNgayBatDau = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserNgayKetThuc = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jRdBtnTrangThaiHuy = new javax.swing.JRadioButton();
        jRdBtnHoatDong = new javax.swing.JRadioButton();
        jRdBtnAllTrangThai = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jRdBtnLocTau = new javax.swing.JRadioButton();
        jComboBoxTau = new javax.swing.JComboBox<>();
        jRdBtnAllTau = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jRdBtnLocTuyen = new javax.swing.JRadioButton();
        jComboBoxTuyenTau = new javax.swing.JComboBox<>();
        jRdBtnAllTuyen = new javax.swing.JRadioButton();
        jPanel_Table = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_LichTrinh = new javax.swing.JTable();

        timePicker1.set24hourMode(true);
        timePicker1.setDisplayText(txtGioDi);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(timePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(timePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gruopForm.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnTimTheoMa.setText("Tìm Theo Mã");
        btnTimTheoMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTheoMaActionPerformed(evt);
            }
        });

        txtMaLichTrinh.setText("Mã Lịch Trình");
        txtMaLichTrinh.setPreferredSize(new java.awt.Dimension(640, 22));
        txtMaLichTrinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLichTrinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(txtMaLichTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnTimTheoMa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTimTheoMa, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(txtMaLichTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        groupBtn.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Cập Nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout groupBtnLayout = new javax.swing.GroupLayout(groupBtn);
        groupBtn.setLayout(groupBtnLayout);
        groupBtnLayout.setHorizontalGroup(
            groupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(groupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        groupBtnLayout.setVerticalGroup(
            groupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        groupText.setBackground(new java.awt.Color(255, 255, 255));
        groupText.setPreferredSize(new java.awt.Dimension(640, 0));

        groupText1.setBackground(new java.awt.Color(255, 255, 255));
        groupText1.setPreferredSize(new java.awt.Dimension(640, 0));

        txtMa.setEnabled(false);
        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mã Lịch Trình");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tên Tàu");

        cbb_Tau.setPreferredSize(new java.awt.Dimension(64, 22));
        cbb_Tau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_TauActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Trạng Thái");

        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbTrangThai.setPreferredSize(new java.awt.Dimension(64, 22));
        cbbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTrangThaiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Ngày Đi");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Giờ Đi");

        txtGioDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGioDiActionPerformed(evt);
            }
        });

        jButtonGioDi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh_HeThong/wall-clock (1).png"))); // NOI18N
        jButtonGioDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGioDiActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Tần suất lịch trình"));
        jPanel8.setToolTipText("");

        btnGrTanSuat.add(jRadioButton6);
        jRadioButton6.setSelected(true);
        jRadioButton6.setText("1 lần");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        btnGrTanSuat.add(jRadioButton9);
        jRadioButton9.setText("Hàng ngày:");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày kết thúc");

        jDateChooser4.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jRadioButton9)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton9)
                        .addComponent(jLabel4))
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout groupText1Layout = new javax.swing.GroupLayout(groupText1);
        groupText1.setLayout(groupText1Layout);
        groupText1Layout.setHorizontalGroup(
            groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupText1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(groupText1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_Tau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                    .addGroup(groupText1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(cbbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groupText1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(groupText1Layout.createSequentialGroup()
                                .addComponent(txtGioDi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGioDi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooserNgayDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(groupText1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(49, 49, 49))
        );
        groupText1Layout.setVerticalGroup(
            groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupText1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(groupText1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jDateChooserNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(19, 19, 19)
                .addGroup(groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_Tau, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGioDi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGioDi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groupText1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(groupText1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupText1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout groupTextLayout = new javax.swing.GroupLayout(groupText);
        groupText.setLayout(groupTextLayout);
        groupTextLayout.setHorizontalGroup(
            groupTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groupText1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                .addContainerGap())
        );
        groupTextLayout.setVerticalGroup(
            groupTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groupText1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_Loc.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setText("Lọc");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Điều kiện lọc"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ngày bắt đầu");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ngày kết thúc");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Trạng thái"));

        btnGroupTrangThai.add(jRdBtnTrangThaiHuy);
        jRdBtnTrangThaiHuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRdBtnTrangThaiHuy.setText("Đã hủy");
        jRdBtnTrangThaiHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtnTrangThaiHuyActionPerformed(evt);
            }
        });

        btnGroupTrangThai.add(jRdBtnHoatDong);
        jRdBtnHoatDong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRdBtnHoatDong.setText("Đang hoạt động");
        jRdBtnHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtnHoatDongActionPerformed(evt);
            }
        });

        btnGroupTrangThai.add(jRdBtnAllTrangThai);
        jRdBtnAllTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRdBtnAllTrangThai.setSelected(true);
        jRdBtnAllTrangThai.setText("Tất cả");
        jRdBtnAllTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtnAllTrangThaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRdBtnTrangThaiHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRdBtnHoatDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRdBtnAllTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jRdBtnTrangThaiHuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRdBtnHoatDong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRdBtnAllTrangThai)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tàu"));

        btnGrTau.add(jRdBtnLocTau);
        jRdBtnLocTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtnLocTauActionPerformed(evt);
            }
        });

        jComboBoxTau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGrTau.add(jRdBtnAllTau);
        jRdBtnAllTau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRdBtnAllTau.setSelected(true);
        jRdBtnAllTau.setText("Tất cả");
        jRdBtnAllTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtnAllTauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRdBtnLocTau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jRdBtnAllTau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRdBtnLocTau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRdBtnAllTau)
                .addGap(20, 20, 20))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tuyến Tàu"));

        btnGrTuyen.add(jRdBtnLocTuyen);
        jRdBtnLocTuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtnLocTuyenActionPerformed(evt);
            }
        });

        jComboBoxTuyenTau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGrTuyen.add(jRdBtnAllTuyen);
        jRdBtnAllTuyen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRdBtnAllTuyen.setSelected(true);
        jRdBtnAllTuyen.setText("Tất cả");
        jRdBtnAllTuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtnAllTuyenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jRdBtnLocTuyen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTuyenTau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jRdBtnAllTuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTuyenTau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRdBtnLocTuyen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRdBtnAllTuyen)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jDateChooserNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(65, 65, 65)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_LocLayout = new javax.swing.GroupLayout(jPanel_Loc);
        jPanel_Loc.setLayout(jPanel_LocLayout);
        jPanel_LocLayout.setHorizontalGroup(
            jPanel_LocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LocLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_LocLayout.setVerticalGroup(
            jPanel_LocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LocLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_LocLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(groupText, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(groupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel_Loc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(groupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(groupText, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout gruopFormLayout = new javax.swing.GroupLayout(gruopForm);
        gruopForm.setLayout(gruopFormLayout);
        gruopFormLayout.setHorizontalGroup(
            gruopFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gruopFormLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        gruopFormLayout.setVerticalGroup(
            gruopFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gruopFormLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel_Table.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setToolTipText("");

        jTable_LichTrinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_LichTrinh.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MaLichTrinh", "Tau", "Gio Di", "Ngay Di", "Tuyen Tau"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_LichTrinh.setRowHeight(40);
        jTable_LichTrinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_LichTrinhMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_LichTrinh);

        javax.swing.GroupLayout jPanel_TableLayout = new javax.swing.GroupLayout(jPanel_Table);
        jPanel_Table.setLayout(jPanel_TableLayout);
        jPanel_TableLayout.setHorizontalGroup(
            jPanel_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_TableLayout.setVerticalGroup(
            jPanel_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_MainLayout = new javax.swing.GroupLayout(jPanel_Main);
        jPanel_Main.setLayout(jPanel_MainLayout);
        jPanel_MainLayout.setHorizontalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gruopForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Table, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_MainLayout.setVerticalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(gruopForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        String tenTau = cbb_Tau.getSelectedItem().toString();
        String gioDiText = txtGioDi.getText(); // Giả sử người dùng nhập "HH:mm"
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
        LocalTime gioDi = LocalTime.parse(gioDiText, formatter);
        LocalDate ngayDi = null;
        LocalDate ngayKetThuc = null;

        try {
            ngayDi = jDateChooserNgayDi.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày đi!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra nếu jRadioButton9 được chọn, lấy ngày kết thúc
        if (jRadioButton9.isSelected()) {
            try {
                ngayKetThuc = jDateChooser4.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày kết thúc!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (ngayKetThuc.isBefore(ngayDi)) {
                JOptionPane.showMessageDialog(this, "Ngày kết thúc phải sau hoặc bằng ngày bắt đầu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String trangThai = cbbTrangThai.getSelectedItem().toString();

        // Kiểm tra các thông tin hợp lệ
        if (tenTau.isEmpty() || gioDi == null || ngayDi == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DAO_ChuyenTau dao = new DAO_ChuyenTau();
        String maTau = dao.getMaTauByTenTau(tenTau); // Lấy mã tàu từ tên tàu

        // Nếu thêm lịch hàng ngày
        if (jRadioButton9.isSelected()) {
            LocalDate currentNgayDi = ngayDi; // Bắt đầu từ ngày được chọn (ngayDi)

            while (!currentNgayDi.isAfter(ngayKetThuc)) {
                int soThuTuChuyen = dao.laySoThuTuChuyenTrongNgay(currentNgayDi, maTau); // Lấy số thứ tự chuyến trong ngày của tàu
                String maLichTrinh = maTau + currentNgayDi.format(DateTimeFormatter.ofPattern("yyMMdd")) + String.format("%02d", soThuTuChuyen + 1);

                // Tạo đối tượng LichTrinhTau
                Tau tau = new Tau(maTau, null, tenTau, 0);
                LichTrinhTau lichTrinh = new LichTrinhTau(maLichTrinh, gioDi, currentNgayDi, tau, trangThai);

                // Thêm vào cơ sở dữ liệu
                boolean isSuccess = dao.themLichTrinh(lichTrinh);

                // Hiển thị thông báo cho từng lần thêm
                if (!isSuccess) {
                    JOptionPane.showMessageDialog(this, "Thêm lịch trình thất bại cho ngày: " + currentNgayDi, "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return; // Dừng nếu gặp lỗi
                }

                // Chuyển sang ngày tiếp theo
                currentNgayDi = currentNgayDi.plusDays(1);
            }

            JOptionPane.showMessageDialog(this, "Thêm lịch trình tàu hàng ngày thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Thêm lịch trình cho một ngày duy nhất
            int soThuTuChuyen = dao.laySoThuTuChuyenTrongNgay(ngayDi, maTau); // Lấy số thứ tự chuyến trong ngày của tàu
            String maLichTrinh = maTau + ngayDi.format(DateTimeFormatter.ofPattern("yyMMdd")) + String.format("%02d", soThuTuChuyen + 1);

            Tau tau = new Tau(maTau, null, tenTau, 0);
            LichTrinhTau lichTrinh = new LichTrinhTau(maLichTrinh, gioDi, ngayDi, tau, trangThai);

            boolean isSuccess = dao.themLichTrinh(lichTrinh);

            if (isSuccess) {
                JOptionPane.showMessageDialog(this, "Thêm lịch trình tàu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Thêm lịch trình tàu thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }

        // Cập nhật bảng và reset các trường nhập liệu
        fillTableWithNewLichTrinh(maTau);
        resetInputFields();
    }

    private void resetInputFields() {
    txtGioDi.setText(""); // Xóa trường giờ đi
    // Xóa trường ngày đi
    cbb_Tau.setSelectedIndex(0); // Chọn lại mục đầu tiên trong ComboBox tàu
    cbbTrangThai.setSelectedIndex(0); // Chọn lại mục đầu tiên trong ComboBox trạng thái
}
    private void fillTableWithNewLichTrinh(String ma) {
    DAO_ChuyenTau lichTrinhDAO = new DAO_ChuyenTau();
      LichTrinhTau lichTrinh = lichTrinhDAO.getTheoMa(ma);

    // Nếu không tìm thấy lịch trình
    if (lichTrinh == null) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy lịch trình với mã: " + ma, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // Điền dữ liệu vào bảng
    DefaultTableModel model = (DefaultTableModel) jTable_LichTrinh.getModel();
    model.setRowCount(0); // Xóa tất cả các dòng hiện tại

     Object[] rowData = new Object[6]; // Giả sử có 6 cột
        
        rowData[0] = lichTrinh.getMaLichTrinh();
        rowData[1] = lichTrinh.getTau().getTenTau(); // Nếu bạn có tên tàu
        rowData[2] = lichTrinh.getGioDi();
        rowData[3] = lichTrinh.getNgayDi();
        rowData[4] = lichTrinh.getTau().getTuyenTau().getTenTuyen(); // Lấy tên tuyến từ đối tượng TuyenTau
        rowData[5] = lichTrinh.getTrangThai();
    
    model.addRow(rowData);
}
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {                                          
         // Lấy thông tin từ các trường nhập liệu
    String gioDiText = txtGioDi.getText(); // Giả sử người dùng nhập "HH:mm"
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
    LocalTime gioDi = LocalTime.parse(gioDiText, formatter);
    
    LocalDate ngayDi = jDateChooserNgayDi.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    String trangThai = cbbTrangThai.getSelectedItem().toString();
    String maLichTrinh = txtMa.getText(); // Giả sử mã lịch trình được nhập vào một trường văn bản

    // Kiểm tra các thông tin hợp lệ
    if (gioDi == null || ngayDi == null || maLichTrinh.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Tạo đối tượng LichTrinhTau với thông tin mới
    LichTrinhTau lichTrinh = new LichTrinhTau(maLichTrinh, gioDi, ngayDi, null, trangThai);
    
    // Cập nhật vào cơ sở dữ liệu
    DAO_ChuyenTau dao = new DAO_ChuyenTau();
    boolean isSuccess = dao.capNhatLichTrinh(lichTrinh);

    // Hiển thị thông báo
    if (isSuccess) {
        JOptionPane.showMessageDialog(this, "Cập nhật lịch trình tàu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        fillTableWithNewLichTrinh(maLichTrinh);
    } else {
        JOptionPane.showMessageDialog(this, "Cập nhật lịch trình tàu thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }                                         

    private void btnTimTheoMaActionPerformed(java.awt.event.ActionEvent evt) {                                             
          String maLichTrinh = txtMaLichTrinh.getText().trim();
    
    if (maLichTrinh.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã lịch trình.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    DAO_ChuyenTau lichTrinhDAO = new DAO_ChuyenTau();
        LichTrinhTau lichTrinh = lichTrinhDAO.getTheoMa(maLichTrinh);

    // Nếu không tìm thấy lịch trình
    if (lichTrinh == null) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy lịch trình với mã: " + maLichTrinh, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // Điền dữ liệu vào bảng
    DefaultTableModel model = (DefaultTableModel) jTable_LichTrinh.getModel();
    model.setRowCount(0); // Xóa tất cả các dòng hiện tại

     Object[] rowData = new Object[6]; // Giả sử có 6 cột
        
        rowData[0] = lichTrinh.getMaLichTrinh();
        rowData[1] = lichTrinh.getTau().getTenTau(); // Nếu bạn có tên tàu
        rowData[2] = lichTrinh.getGioDi();
        rowData[3] = lichTrinh.getNgayDi();
        rowData[4] = lichTrinh.getTau().getTuyenTau().getTenTuyen(); // Lấy tên tuyến từ đối tượng TuyenTau
        rowData[5] = lichTrinh.getTrangThai();
    
    model.addRow(rowData);
    }                                            

    private void txtMaLichTrinhActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void jRdBtnAllTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void jRdBtnTrangThaiHuyActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void jRdBtnHoatDongActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void jRdBtnLocTauActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jRdBtnAllTauActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jRdBtnLocTuyenActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void jRdBtnAllTuyenActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void cbbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jButtonGioDiActionPerformed(java.awt.event.ActionEvent evt) {
        SwingUtilities.invokeLater(() -> {

            timePicker1.showPopup(jButtonGioDi, 100, 100);
        });

    }                                            

    private void txtGioDiActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        jDateChooser4.setEnabled(true);
    }
    private void jRadioButton9MouseClicked(java.awt.event.MouseEvent evt) {

    }
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
         // Xóa các trường văn bản
        txtMa.setText("");           // Xóa mã lịch trình
        txtGioDi.setText("");        // Xóa giờ đi
     
    
    // Đặt lại ComboBox về giá trị mặc định
        cbb_Tau.setSelectedIndex(0); // Giả sử bạn muốn đặt lại về mục đầu tiên
        cbbTrangThai.setSelectedIndex(0); // Đặt trạng thái về mục đầu tiên, nếu cần

    // Kích hoạt lại ComboBox mã tàu nếu trước đó đã bị vô hiệu hóa
    cbb_Tau.setEnabled(true); // Kích hoạt lại nếu đã bị vô hiệu hóa
    btnAdd.setEnabled(true);
     jTable_LichTrinh.clearSelection();
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        DAO_ChuyenTau dao= new DAO_ChuyenTau();
        Date startDate = jDateChooserNgayBatDau.getDate();
        Date endDate = jDateChooserNgayKetThuc.getDate();
        
        LocalDate localStartDate = null;
        LocalDate localEndDate = null;

        // Chuyển Date thành LocalDate
        if (startDate != null) {
            localStartDate = startDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        
        if (endDate != null) {
            localEndDate = endDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }

        // Lấy giá trị tên tuyến từ jComboBoxTuyenTau
        String tenTuyen = jComboBoxTuyenTau.getSelectedItem().toString();
        
        // Lấy giá trị tên tàu từ jComboBoxTau
        String tenTau = jComboBoxTau.getSelectedItem().toString();

        // Xử lý lọc theo tàu
        boolean locTau = jRdBtnLocTau.isSelected();
        
        // Xử lý lọc theo trạng thái
        String trangThai = null;
        if (jRdBtnTrangThaiHuy.isSelected()) {
            trangThai = "Hủy";
        } else if (jRdBtnHoatDong.isSelected()) {
            trangThai = "Hoạt động";
        } else if (jRdBtnAllTrangThai.isSelected()) {
            trangThai = "Tất cả";
        }

        // Xử lý lọc theo tuyến
        boolean locTuyen = jRdBtnLocTuyen.isSelected();
        DefaultTableModel model = (DefaultTableModel) jTable_LichTrinh.getModel();
        // Kiểm tra xem các giá trị đã được chọn chưa
        if (localStartDate != null && localEndDate != null) {
            // Gọi phương thức DAO để lấy dữ liệu
            List<LichTrinhTau> ketQua = dao.locLichTrinhTau(localStartDate, localEndDate, tenTau, tenTuyen, locTau, locTuyen, trangThai);
            if (ketQua.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không có lịch trình nào");
                model.setRowCount(0);
} else {
  
    model.setRowCount(0); // Xóa tất cả các dòng hiện tại

// Duyệt qua danh sách và thêm từng đối tượng vào bảng
for (LichTrinhTau lichTrinh : ketQua) {
    Object[] rowData = new Object[6]; // Giả sử có 6 cột

    // Điền dữ liệu vào rowData
    rowData[0] = lichTrinh.getMaLichTrinh(); // Mã lịch trình
    rowData[1] = lichTrinh.getTau().getTenTau(); // Tên tàu
    rowData[2] = lichTrinh.getGioDi(); // Giờ đi
    rowData[3] = lichTrinh.getNgayDi(); // Ngày đi
    rowData[4] = lichTrinh.getTau().getTuyenTau().getTenTuyen(); // Tên tuyến
    rowData[5] = lichTrinh.getTrangThai(); // Trạng thái

    // Thêm dòng vào mô hình
    model.addRow(rowData);
}

// Nếu bạn cần cập nhật lại giao diện bảng, có thể gọi phương thức repaint()
jTable_LichTrinh.revalidate(); // Cập nhật lại bảng
jTable_LichTrinh.repaint(); // Vẽ lại bảng
}
            // Hiển thị dữ liệu lọc ra bảng hoặc xử lý khác
            
        } else {
            JOptionPane.showMessageDialog(this,"Vui lòng chọn ngày bắt đầu và ngày kết thúc.");
        }
     
    }                                        

    private void jTable_LichTrinhMouseClicked(java.awt.event.MouseEvent evt) {                                              
        int row =  jTable_LichTrinh.getSelectedRow();
		txtMa.setText(jTable_LichTrinh.getValueAt(row, 0).toString());
		txtGioDi.setText(jTable_LichTrinh.getValueAt(row, 2).toString());
		cbb_Tau.setSelectedItem(jTable_LichTrinh.getValueAt(row, 1).toString());
                Object value = jTable_LichTrinh.getValueAt(row, 3);
                LocalDate localDate = (LocalDate) value; // Chuyển đổi về LocalDate
                Date date = java.sql.Date.valueOf(localDate); // Chuyển đổi LocalDate sang Date
                jDateChooserNgayDi.setDate(date); // Đặt giá trị cho JDateChooser
                cbb_Tau.setEnabled(false);
                btnAdd.setEnabled(false);
           
    }                                             

    private void cbb_TauActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       
    public void fillComboBoxTau() {
        DAO_ChuyenTau dao = new DAO_ChuyenTau();
        List<Tau> listTau = dao.getAllTau(); // Gọi phương thức lấy dữ liệu tàu

        jComboBoxTau.removeAllItems(); // Xóa các mục hiện tại trong ComboBox

        // Sử dụng Set để theo dõi các tên tàu đã thêm
        Set<String> uniqueTauNames = new HashSet<>();

        for (Tau tau : listTau) {
            String tenTau = tau.getTenTau();
            // Kiểm tra nếu tên tàu chưa được thêm vào Set
            if (uniqueTauNames.add(tenTau)) {
                jComboBoxTau.addItem(tenTau);
                cbb_Tau.addItem(tenTau);// Thêm tên tàu vào ComboBox nếu chưa tồn tại
            }
        }
    }
public void fillComboBoxTrangThai() {
    DAO_ChuyenTau dao = new DAO_ChuyenTau(); // Giả sử bạn có lớp MyConnection để lấy kết nối
    List<String> listTrangThai = dao.getAllTrangThai(); // Gọi phương thức lấy dữ liệu trạng thái

    cbbTrangThai.removeAllItems(); // Xóa các mục hiện tại trong ComboBox

    for (String trangThai : listTrangThai) {
        cbbTrangThai.addItem(trangThai); // Thêm trạng thái vào ComboBox
    }
}
    public void fillComboBoxTuyenTau() {
          DAO_ChuyenTau dao= new DAO_ChuyenTau();
        List<TuyenTau> listTuyenTau = dao.getAllTuyenTau(); // Lấy danh sách các tuyến tàu
    
    // Xóa tất cả các item trước khi thêm mới
        jComboBoxTuyenTau.removeAllItems();
    
    // Thêm các tuyến tàu vào JComboBox
        for (TuyenTau tuyenTau : listTuyenTau) {
        jComboBoxTuyenTau.addItem(tuyenTau.getTenTuyen()); // Thêm tên tuyến tàu vào JComboBox
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuyenTau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuyenTau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuyenTau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenTau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChuyenTau().setVisible(true);
                
            }
           
        });
    }
    public Component getjPanelMain() {
        return jPanel_Main;
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup btnGrTanSuat;
    private javax.swing.ButtonGroup btnGrTau;
    private javax.swing.ButtonGroup btnGrTuyen;
    private javax.swing.ButtonGroup btnGroupTrangThai;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTimTheoMa;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JComboBox<String> cbb_Tau;
    private javax.swing.JPanel groupBtn;
    private javax.swing.JPanel groupText;
    private javax.swing.JPanel groupText1;
    private javax.swing.JPanel gruopForm;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonGioDi;
    private javax.swing.JComboBox<String> jComboBoxTau;
    private javax.swing.JComboBox<String> jComboBoxTuyenTau;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooserNgayBatDau;
    private com.toedter.calendar.JDateChooser jDateChooserNgayDi;
    private com.toedter.calendar.JDateChooser jDateChooserNgayKetThuc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel_Loc;
    private javax.swing.JPanel jPanel_Main;
    private javax.swing.JPanel jPanel_Table;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JRadioButton jRdBtnAllTau;
    private javax.swing.JRadioButton jRdBtnAllTrangThai;
    private javax.swing.JRadioButton jRdBtnAllTuyen;
    private javax.swing.JRadioButton jRdBtnHoatDong;
    private javax.swing.JRadioButton jRdBtnLocTau;
    private javax.swing.JRadioButton jRdBtnLocTuyen;
    private javax.swing.JRadioButton jRdBtnTrangThaiHuy;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_LichTrinh;
    private com.raven.swing.TimePicker timePicker1;
    private javax.swing.JTextField txtGioDi;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMaLichTrinh;
    // End of variables declaration                   
    
}
