/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.DAO_TraCuuHD;
import Database.ConnectDatabase;
import Entity.HoaDon;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.awt.*;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;

/**
 *
 * @author viet6
 */
public class Frm_TraCuuHoaDon extends JFrame {

    private final DAO_TraCuuHD dao_traCuuHD;
    private final DefaultTableModel tableModel;
    private List<HoaDon> hoaDons;

    /**
     * Creates new form Frm_TraCuuHoaDon
     */
    public Frm_TraCuuHoaDon() {
        initComponents();
                 try {
            ConnectDatabase.getInstance().connect();    
        } catch (Exception e) {

        }
        dao_traCuuHD = new DAO_TraCuuHD();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        tableModel = (DefaultTableModel)tableHoaDon.getModel();
        
        tableHoaDon.setFont(new Font("Arial", Font.PLAIN, 14));
        tableHoaDon.setRowHeight(35);  // Đặt chiều cao của các hàng (ví dụ: 35)
        tableHoaDon.setSelectionBackground(new Color(255, 223, 186));  // Màu nền khi chọn hàng
                // Thay đổi màu của tiêu đề cột
        JTableHeader header = tableHoaDon.getTableHeader();
        header.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                                                           boolean isSelected, boolean hasFocus,
                                                           int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setBackground(new Color(0, 131, 66)); // Màu nền tiêu đề cột
                c.setForeground(Color.white);          // Màu chữ tiêu đề cột
                c.setFont(new Font("Arial", Font.BOLD, 20)); // Font chữ tiêu đề
                ((JLabel) c).setHorizontalAlignment(SwingConstants.CENTER); // Căn giữa
                return c;
            }
        });
        Color colorTieuDeBang = new Color(0, 131, 66);
        header.setBackground(Color.BLUE); // Màu nền tiêu đề cột
        header.setForeground(Color.WHITE); // Màu chữ tiêu đề cột
        header.setFont(new Font("Arial", Font.BOLD, 20)); // Đặt font cho tiêu đề (cỡ 16)
        tableHoaDon.setFont(new Font("Arial", Font.PLAIN, 18)); // Đặt font cho các dòng (cỡ 14)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableHoaDon = new JTable();
        jPanelFind = new javax.swing.JPanel();
        txtNhapMa = new javax.swing.JTextField();
        btnTimVe = new javax.swing.JButton();
        rdCCCD = new javax.swing.JRadioButton();
        rdMaHD = new javax.swing.JRadioButton();
        rdHDHuyDoi = new javax.swing.JRadioButton();
        rdMaKM = new javax.swing.JRadioButton();
        lblThongTinVe = new JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLocHoaDon = new javax.swing.JButton();
        jLabel7 = new JLabel();
        jDateChooseLocNBD = new com.toedter.calendar.JDateChooser();
        jLabel8 = new JLabel();
        jDateChooserLocNKT = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        lblTongTien = new JLabel();
        jLabel1 = new JLabel();
        txtMaxCost = new javax.swing.JTextField();
        txtMinCost = new javax.swing.JTextField();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnHDtoday = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new JLabel();
        jPanelMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableHoaDon.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàng", "Mã khuyến mãi", "Loại hóa đơn", "Ngày hóa đơn", "Tiền khuyến mãi", "Tổng tiền"
            }
        ));
        jScrollPane4.setViewportView(tableHoaDon);

        jPanelFind.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        btnTimVe.setBackground(new Color(0, 131, 66));
        btnTimVe.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        btnTimVe.setForeground(new Color(255, 255, 255));
        btnTimVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh_HeThong/findNV.png"))); // NOI18N
        btnTimVe.setText("Tra cứu");
        btnTimVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimVeMouseClicked(evt);
            }
        });
        btnTimVe.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimVeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdCCCD);
        rdCCCD.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        rdCCCD.setText("CCCD");
        rdCCCD.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCCCDActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdMaHD);
        rdMaHD.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        rdMaHD.setText("Mã hóa đơn");
        rdMaHD.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMaHDActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdHDHuyDoi);
        rdHDHuyDoi.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        rdHDHuyDoi.setText("HD hủy");
        rdHDHuyDoi.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdHDHuyDoiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdMaKM);
        rdMaKM.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        rdMaKM.setSelected(true);
        rdMaKM.setText("Mã khuyến mãi");
        rdMaKM.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMaKMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFindLayout = new javax.swing.GroupLayout(jPanelFind);
        jPanelFind.setLayout(jPanelFindLayout);
        jPanelFindLayout.setHorizontalGroup(
            jPanelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFindLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdHDHuyDoi)
                    .addGroup(jPanelFindLayout.createSequentialGroup()
                        .addGroup(jPanelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdCCCD)
                            .addComponent(rdMaKM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNhapMa, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnTimVe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rdMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanelFindLayout.setVerticalGroup(
            jPanelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFindLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rdMaHD)
                .addGroup(jPanelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFindLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNhapMa, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimVe, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFindLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(rdMaKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdCCCD)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdHDHuyDoi)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblThongTinVe.setFont(new Font("Segoe UI", 2, 24)); // NOI18N
        lblThongTinVe.setText("Thông tin hóa đơn");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        btnLocHoaDon.setBackground(new Color(0, 131, 66));
        btnLocHoaDon.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        btnLocHoaDon.setForeground(new Color(255, 255, 255));
        btnLocHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh_HeThong/filterNV.png"))); // NOI18N
        btnLocHoaDon.setText("Lọc");
        btnLocHoaDon.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocHoaDonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Ngày bắt đầu:");

        jDateChooseLocNBD.setFont(new Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Ngày kết thúc:");

        jPanel3.setBackground(new Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lblTongTien.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        lblTongTien.setText("Tổng tiền từ: ");

        jLabel1.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("-");

        txtMinCost.setMinimumSize(new java.awt.Dimension(70, 30));
        txtMinCost.setPreferredSize(new java.awt.Dimension(70, 30));

        btn3.setText("1000-2000k");
        btn3.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn1.setText("0-500k");
        btn1.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("500-1000k");
        btn2.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMinCost, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaxCost, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaxCost, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinCost, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserLocNKT, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooseLocNBD, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(btnLocHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jDateChooseLocNBD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserLocNKT, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnLocHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnHDtoday.setBackground(new Color(0, 131, 66));
        btnHDtoday.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        btnHDtoday.setForeground(new Color(255, 255, 255));
        btnHDtoday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh_HeThong/iconDoiVe.png"))); // NOI18N
        btnHDtoday.setText("Hóa đơn hôm nay");
        btnHDtoday.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDtodayActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new Color(0, 131, 66));

        jLabel2.setFont(new Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setText("TRA CỨU HÓA ĐƠN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(417, 417, 417))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanelFind, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblThongTinVe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHDtoday)))
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanelFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHDtoday, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThongTinVe))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(250, 2));

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimVeMouseClicked

    }//GEN-LAST:event_btnTimVeMouseClicked

    private void btnTimVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimVeActionPerformed
        // TODO add your handling code here:
               // Lấy giá trị từ txtNhapMa
        String maNhap = txtNhapMa.getText().trim(); // Lấy và làm sạch dữ liệu nhập vào

        // Kiểm tra nếu txtNhapMa không rỗng
        if (maNhap.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin tìm kiếm.");
            return; // Dừng nếu không có giá trị
        }

        // Kiểm tra radio nào được chọn và thực hiện hành động tương ứng
        if (rdCCCD.isSelected()) {
            // Thực hiện tìm kiếm theo CCCD
           hoaDons = dao_traCuuHD.timHoaDonTheoCCCD(maNhap);
           if(hoaDons== null){
                JOptionPane.showMessageDialog(null, "Không tìm thấy hóa đơn với cccd");
           }
        } else if (rdHDHuyDoi.isSelected()) {
            // Thực hiện tìm kiếm theo mã hóa đơn hủy đổi
            hoaDons =dao_traCuuHD.timHoaDonTheoMaLHD("LHD03");
             if(hoaDons== null){
                JOptionPane.showMessageDialog(null, "Không tìm thấy hóa đơn hủy");
           }
        } else if (rdMaHD.isSelected()) {
            // Thực hiện tìm kiếm theo mã hóa đơn
           hoaDons = (List<HoaDon>) dao_traCuuHD.timHoaDonTheoMaHD(maNhap);
            if(hoaDons== null){
                JOptionPane.showMessageDialog(null, "Không tìm thấy hóa đơn với mã hóa đơn");
           }
        } else if (rdMaKM.isSelected()) {
            // Thực hiện tìm kiếm theo mã khuyến mãi
            hoaDons = dao_traCuuHD.timHoaDonTheoMaKM(maNhap);
             if(hoaDons== null){
                JOptionPane.showMessageDialog(null, "Không tìm thấy hóa đơn với mã khuyến mãi");
           }
        } else {
            // Nếu không có radio nào được chọn
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một tiêu chí tìm kiếm.");
        }
          themThongTinVaoTable(hoaDons);
    }//GEN-LAST:event_btnTimVeActionPerformed

    private void rdCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdCCCDActionPerformed

    private void rdHDHuyDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdHDHuyDoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdHDHuyDoiActionPerformed

    private void rdMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMaHDActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        txtMaxCost.setText("1000000");  // Đặt giá trị cho txtMaxCost
        txtMinCost.setText("500000");    // Đặt giá trị cho txtMinCost
    }//GEN-LAST:event_btn2ActionPerformed

    private void rdMaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMaKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMaKMActionPerformed

    private void btnHDtodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDtodayActionPerformed
        // TODO add your handling code here:
            List<HoaDon> hoaDons = dao_traCuuHD.timHoaDonTheoNgayHienTai();
             themThongTinVaoTable(hoaDons);
    }//GEN-LAST:event_btnHDtodayActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        txtMaxCost.setText("500000");  // Đặt giá trị cho txtMaxCost
        txtMinCost.setText("0");    // Đặt giá trị cho txtMinCost
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        txtMaxCost.setText("2000000");  // Đặt giá trị cho txtMaxCost
        txtMinCost.setText("1000000");    // Đặt giá trị cho txtMinCost
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnLocHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocHoaDonActionPerformed
        // Lấy ngày bắt đầu và ngày kết thúc từ các bộ chọn ngày
    Date ngayBatDau = jDateChooseLocNBD.getDate();
    Date ngayKetThuc = jDateChooserLocNKT.getDate();

    // Kiểm tra nếu ngày bắt đầu lớn hơn ngày kết thúc
    if (ngayBatDau != null && ngayKetThuc != null) {
        // Chuyển đổi Date thành LocalDate
        LocalDate startDate = ngayBatDau.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate endDate = ngayKetThuc.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        // Kiểm tra nếu ngày bắt đầu sau ngày kết thúc
        if (startDate.isAfter(endDate)) {
            JOptionPane.showMessageDialog(null, "Ngày bắt đầu không được sau ngày kết thúc.");
            return;  // Dừng hàm nếu ngày không hợp lệ
        }

        // Lấy giá trị từ các JTextField txtMaxCost và txtMinCost
        String minCostText = txtMinCost.getText();
        String maxCostText = txtMaxCost.getText();
        
        double minCost = 0.0;
        double maxCost = Double.MAX_VALUE;

        // Kiểm tra nếu người dùng nhập giá trị tối thiểu và tối đa
        try {
            if (!minCostText.isEmpty()) {
                minCost = Double.parseDouble(minCostText);  // Chuyển đổi giá trị nhập thành double
            }
            if (!maxCostText.isEmpty()) {
                maxCost = Double.parseDouble(maxCostText);  // Chuyển đổi giá trị nhập thành double
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập giá trị hợp lệ cho mức giá.");
            return;  // Dừng nếu giá trị không hợp lệ
        }

        // Gọi hàm lọc để lấy danh sách hóa đơn trong khoảng thời gian và theo mức giá
        List<HoaDon> hoaDons = dao_traCuuHD.timHoaDonTheoKhoangThoiGian(startDate, endDate, minCost, maxCost);
        
        // Thêm thông tin vào bảng
        themThongTinVaoTable(hoaDons);
    } else {
        // Thông báo nếu người dùng chưa chọn cả ngày bắt đầu và ngày kết thúc
        JOptionPane.showMessageDialog(null, "Vui lòng chọn cả ngày bắt đầu và ngày kết thúc.");
    }
    }//GEN-LAST:event_btnLocHoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_TraCuuHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_TraCuuHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_TraCuuHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_TraCuuHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_TraCuuHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Component getJpannelTraCuuHD() {
        return jPanel1;
    }

    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btnHDtoday;
    private javax.swing.JButton btnLocHoaDon;
    private javax.swing.JButton btnTimVe;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDateChooseLocNBD;
    private com.toedter.calendar.JDateChooser jDateChooserLocNKT;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelFind;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JScrollPane jScrollPane4;
    private JLabel lblThongTinVe;
    private JLabel lblTongTien;
    private javax.swing.JRadioButton rdCCCD;
    private javax.swing.JRadioButton rdHDHuyDoi;
    private javax.swing.JRadioButton rdMaHD;
    private javax.swing.JRadioButton rdMaKM;
    private JTable tableHoaDon;
    private javax.swing.JTextField txtMaxCost;
    private javax.swing.JTextField txtMinCost;
    private javax.swing.JTextField txtNhapMa;
    // End of variables declaration//GEN-END:variables

    private void themThongTinVaoTable(List<HoaDon> hoaDons) {
                // Xóa tất cả các dòng hiện tại trong bảng trước khi thêm dữ liệu mới
             tableModel.setRowCount(0);
             // Duyệt qua danh sách các hóa đơn và thêm vào tableModel
         for (HoaDon hoaDon : hoaDons) {
             String tenLoai;

             // Kiểm tra điều kiện và xác định giá trị của tenLoai
             if (hoaDon.getLoaiHoaDon().getMaLoaiHoaDon().equals("LHD01")) {
                 tenLoai = "Thanh toán";
             } else {
                 tenLoai = "Trả Vé";
             }

             // Tạo mảng rowData với các giá trị từ hoaDon
             Object[] rowData = new Object[] {
                 hoaDon.getMaHD(),
                 hoaDon.getKhachHang().getTenKhachHang(),
                 hoaDon.getKhuyenMai().getMaKM(),
                 tenLoai,  // Đưa giá trị tenLoai đã xác định vào đây
                 hoaDon.getNgayLap(),
                 hoaDon.getTienGiam(),
                 hoaDon.getTongTien()
             };

             // Thêm dòng vào tableModel
             tableModel.addRow(rowData);
         }

    }
}
