/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.DAO_NhanVien;
import DAO.DAO_TaiKhoan;
import Database.ConnectDatabase;
import Entity.NhanVien;
import Entity.TaiKhoan;
import helper.MessageDialogHelper;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author viet6
 */
public class FrmNhanVien extends JFrame {

    private String fileName = "avataMacDinh";
    private String filePath = "";
    private DAO_NhanVien nv_dao;
    private DAO_TaiKhoan tk_dao ;

    /**
     * Creates new form NhanVien
     */
    public FrmNhanVien()  {
         initComponents();
        try {
            ConnectDatabase.getInstance().connect();    
        } catch (Exception e) {

        }
        nv_dao = new DAO_NhanVien();
        tk_dao = new DAO_TaiKhoan();
       
        
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        try {
            //lblChucVu.setText("Chức vụ:");
            txtMaNhanVien.setText(phatSinhMaNVTuDong());
        } catch (Exception ex) {
            Logger.getLogger(FrmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            hienThiDanhSachNhanVien(nv_dao.findAll());
        } catch (Exception ex) {
              System.out.println("rong)");
            Logger.getLogger(FrmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*private FrmNhanVien() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }*/

//    public FrmNhanVien(NhanVien nv) throws Exception {
//        initComponents();
//        // Hiển thị thông tin nhân viên, ví dụ:
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
//        lblChucVu.setText("Chức vụ: " + nv.getChucVu());
//        lblHoTen.setText("Họ tên: " + nv.getTenNV());
//        txtMaNhanVien.setText(phatSinhMaNVTuDong());
//        hienThiDanhSachNhanVien(nv_dao.findAll());
//        // Bạn có thể hiển thị thêm thông tin khác nếu cần
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new JLabel();
        lblChucVu = new JLabel();
        lblHoTen = new JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtMaNhanVien = new javax.swing.JTextField();
        jLabel2 = new JLabel();
        jLabel7 = new JLabel();
        jLabel6 = new JLabel();
        jLabel5 = new JLabel();
        dcsNgayVaoLam = new com.toedter.calendar.JDateChooser();
        txtCMND = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        cbxChucVu = new javax.swing.JComboBox<>();
        cbxTrangThai = new javax.swing.JComboBox<>();
        txtTenNV = new javax.swing.JTextField();
        jLabel4 = new JLabel();
        jLabel10 = new JLabel();
        jLabel8 = new JLabel();
        jLabel11 = new JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblAvata = new JLabel();
        btnAvata = new javax.swing.JButton();
        txtSDT = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnLamMoi = new javax.swing.JButton();
        btnThemm = new javax.swing.JButton();
        jLabel9 = new JLabel();
        btnCapNhat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableNhanVien = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(19, 78, 44));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lý nhân viên");

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(lblHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(288, 288, 288)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        txtMaNhanVien.setEditable(false);
        txtMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhanVienActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã nhân viên:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("SDT:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("CCCD:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Ngày vào làm:");

        dcsNgayVaoLam.setBackground(new java.awt.Color(204, 204, 204));
        dcsNgayVaoLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtCMND.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMNDActionPerformed(evt);
            }
        });

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        cbxChucVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quan Ly", "Nhan Vien" }));
        cbxChucVu.setPreferredSize(new java.awt.Dimension(100, 50));
        cbxChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxChucVuActionPerformed(evt);
            }
        });

        cbxTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dang lam", "Nghi viec", " " }));
        cbxTrangThai.setPreferredSize(new java.awt.Dimension(100, 50));
        cbxTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTrangThaiActionPerformed(evt);
            }
        });

        txtTenNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenNV.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Họ tên:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Trạng thái:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Địa chỉ:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Chức vụ:");

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        lblAvata.setIcon(new ImageIcon(getClass().getResource("/Anh_HeThong/avataMacDinh.png"))); // NOI18N

        btnAvata.setBackground(new java.awt.Color(255, 51, 51));
        btnAvata.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAvata.setForeground(new java.awt.Color(255, 255, 255));
        btnAvata.setText("Chọn hình");
        btnAvata.setBorder(new javax.swing.border.MatteBorder(null));
        btnAvata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblAvata, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvata, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvata, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvata, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCMND)
                    .addComponent(dcsNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(258, 258, 258))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cbxTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(cbxChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcsNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnTim.setBackground(new java.awt.Color(204, 255, 255));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTim.setIcon(new ImageIcon(getClass().getResource("/Anh_HeThong/findNV.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 1088, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        btnLamMoi.setBackground(new java.awt.Color(52, 213, 209));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLamMoi.setIcon(new ImageIcon(getClass().getResource("/Anh_HeThong/undo.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThemm.setBackground(new java.awt.Color(255, 255, 204));
        btnThemm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemm.setIcon(new ImageIcon(getClass().getResource("/Anh_HeThong/plus (1).png"))); // NOI18N
        btnThemm.setText("Thêm");
        btnThemm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemmActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(255, 153, 153));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCapNhat.setIcon(new ImageIcon(getClass().getResource("/Anh_HeThong/circular-arrow.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(45, 45, 45)
                .addComponent(btnThemm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));

        TableNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TableNhanVien.setRowHeight(50);
        TableNhanVien.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên", "Số điện thoại", "Trạng thái", "CCCD", "Địa chỉ", "Ngày vào làm", "Chức vụ", "Avata"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, String.class, String.class, Object.class, String.class, Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        javax.swing.table.JTableHeader header = TableNhanVien.getTableHeader();
        header.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 20));
        TableNhanVien.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                TableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableNhanVien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1477, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        String tuKhoa = txtTimKiem.getText().trim().toLowerCase();
        if (tuKhoa.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập từ khóa tìm kiếm!");
            return;
        }

        List<NhanVien> ketQuaTimKiem = new ArrayList<>();
        try {
            List<NhanVien> danhSachNhanVien = nv_dao.findAll();
            for (NhanVien nv : danhSachNhanVien) {
                if (nv.getMaNhanVien().toLowerCase().contains(tuKhoa)
                        || nv.getTenNV().toLowerCase().contains(tuKhoa)
                        || nv.getSoDT().toLowerCase().contains(tuKhoa)
                        || nv.getCCCD().toLowerCase().contains(tuKhoa)) {
                    ketQuaTimKiem.add(nv);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (ketQuaTimKiem.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy nhân viên phù hợp!");
        } else {
            hienThiDanhSachNhanVien(ketQuaTimKiem);
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void TableNhanVienMouseClicked(MouseEvent evt) {//GEN-FIRST:event_TableNhanVienMouseClicked
        int row = TableNhanVien.rowAtPoint(evt.getPoint());
        if (row >= 0) {
            // Lấy dữ liệu từ các cột của dòng đã chọn
            String maNV = TableNhanVien.getValueAt(row, 0).toString();
            String tenNV = TableNhanVien.getValueAt(row, 1).toString();
            String soDT = TableNhanVien.getValueAt(row, 2).toString();
            String trangThai = TableNhanVien.getValueAt(row, 3).toString();
            String cccd = TableNhanVien.getValueAt(row, 4).toString();
            String diaChi = TableNhanVien.getValueAt(row, 5).toString();
            String ngayVaoLam = TableNhanVien.getValueAt(row, 6).toString();
            String chucVu = TableNhanVien.getValueAt(row, 7).toString();
            String avata = TableNhanVien.getValueAt(row, 8).toString();

            // Cập nhật các JTextField và ComboBox
            txtMaNhanVien.setText(maNV);
            txtTenNV.setText(tenNV);
            txtSDT.setText(soDT);
            cbxTrangThai.setSelectedItem(trangThai);
            txtCMND.setText(cccd);
            txtDiaChi.setText(diaChi);
            cbxChucVu.setSelectedItem(chucVu);
            // Cập nhật ngày vào làm (dạng DatePicker)
            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date date = dateFormat.parse(ngayVaoLam);
                dcsNgayVaoLam.setDate(date);
            } catch (ParseException e) {
                e.printStackTrace();
            }

            cbxChucVu.setSelectedItem(chucVu);
            lblAvata.setHorizontalAlignment(JLabel.CENTER);
            lblAvata.setVerticalAlignment(JLabel.CENTER);

            if (new File("src/Anh_HeThong/" + avata).exists()) {
                // Nếu file ảnh tồn tại trong thư mục /Anh_HeThong/
                lblAvata.setIcon(new ImageIcon(getClass().getResource("/Anh_HeThong/" + avata)));
            } else {
                // Nếu không, sử dụng đường dẫn tuyệt đối
                lblAvata.setIcon(new ImageIcon(filePath)); // 'avata' ở đây là đường dẫn tuyệt đối
            }

        }
    }//GEN-LAST:event_TableNhanVienMouseClicked

    private void btnThemmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemmActionPerformed
        try {
            List<NhanVien> dsNV = nv_dao.findAll();
            hienThiDanhSachNhanVien(dsNV);

            if (checkData()) {
                String maNV = txtMaNhanVien.getText();
                String tenNV = txtTenNV.getText();
                LocalDate ngayVaoLam = dcsNgayVaoLam.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                String cmnd = txtCMND.getText();
                String sdt = txtSDT.getText();
                String diaChi = txtDiaChi.getText();
                String trangThai = (String) cbxTrangThai.getSelectedItem();
                String chucVu = (String) cbxChucVu.getSelectedItem();
                String avatar = "";

                // Sử dụng avatarPath thay vì icon.getDescription()
                if (filePath != null && !filePath.isEmpty()) {
                    avatar = new File(fileName).getName();
                } else {
                    avatar = "default-avatar.jpg";
                }

                NhanVien nv = new NhanVien(maNV, tenNV, sdt, trangThai, cmnd, diaChi, ngayVaoLam, chucVu, avatar);

                if (nv_dao.insert(nv)) {
                    TaiKhoan tk = new TaiKhoan(maNV, "11111111");
                    tk_dao.insert(tk);
                    MessageDialogHelper.showMessageDialog(this, "Thêm nhân viên thành công", "Thông báo");
                    hienThiDanhSachNhanVien(nv_dao.findAll());
                } else {
                    MessageDialogHelper.showMessageDialog(this, "Thêm nhân viên thất bại", "Cảnh báo");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnThemmActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        try {
            // Lấy dữ liệu từ form
            String maNV = txtMaNhanVien.getText();  // Mã nhân viên
            String tenNV = txtTenNV.getText();  // Tên nhân viên
            String soDT = txtSDT.getText();  // Số điện thoại
            String trangThai = (String) cbxTrangThai.getSelectedItem();  // Trạng thái
            String cccd = txtCMND.getText();  // CMND/CCCD
            String diaChi = txtDiaChi.getText();  // Địa chỉ
            LocalDate ngayVaoLam = dcsNgayVaoLam.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();  // Ngày vào làm
            String chucVu = (String) cbxChucVu.getSelectedItem();  // Chức vụ
            String avata = fileName;
            System.out.println("name avata:" + lblAvata);
            // Tạo đối tượng NhanVien từ dữ liệu lấy từ form
            NhanVien nv = new NhanVien(maNV, tenNV, soDT, trangThai, cccd, diaChi, ngayVaoLam, chucVu, avata);

            // Cập nhật thông tin nhân viên vào cơ sở dữ liệu
            if (nv_dao.update(nv)) {
                MessageDialogHelper.showMessageDialog(this, "Cập nhật nhân viên thành công", "Thông báo");
                hienThiDanhSachNhanVien(nv_dao.findAll());  // Cập nhật lại bảng dữ liệu
            } else {
                MessageDialogHelper.showMessageDialog(this, "Cập nhật nhân viên thất bại, chọn dòng cần cập nhật", "Cảnh báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        }

    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        try {
            // Tự động sinh mã nhân viên
            txtMaNhanVien.setText(phatSinhMaNVTuDong());
        } catch (Exception ex) {
            Logger.getLogger(FrmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Làm mới các trường thông tin
        txtTenNV.setText("");
        txtSDT.setText("");
        txtCMND.setText("");
        txtDiaChi.setText("");
        txtTimKiem.setText("");

        // Đặt lại trạng thái cho ComboBox
        cbxTrangThai.setSelectedIndex(0);
        cbxChucVu.setSelectedIndex(0);

        // Đặt lại ngày vào làm về ngày hiện tại
        dcsNgayVaoLam.setDate(new Date());

        // Xóa chọn các radio button
        buttonGroup1.clearSelection();

        // Đặt lại focus cho trường mã nhân viên
        txtMaNhanVien.requestFocus();

        // Đặt lại avatar về mặc định
        lblAvata.setIcon(new ImageIcon(getClass().getResource("/Anh_heThong/avataMacDinh.png")));
//        try {
//            hienThiDanhSachNhanVien(nv_dao.findAll());
//        } catch (Exception ex) {
//            Logger.getLogger(FrmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void cbxTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTrangThaiActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMNDActionPerformed

    private void txtMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhanVienActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void cbxChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxChucVuActionPerformed

    private void btnAvataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvataActionPerformed
        JFileChooser avata = new JFileChooser();   // chọn ảnh từ máy
        avata.setDialogTitle("Chọn ảnh đại diện");
        avata.setFileFilter(new FileNameExtensionFilter("Ảnh đại diện", "jpg", "png", "jpeg"));

        int result = avata.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {  // lấy đường dẫn tuyệt đối
            File selectedFile = avata.getSelectedFile();
            System.out.println("selectedFile:" + selectedFile);
            filePath = selectedFile.getPath();
            System.out.println("filePath:" + filePath);
            // Hiển thị ảnh trong lblAvata
            ImageIcon imageIcon = new ImageIcon(filePath);  // tạo ảnh từ đường dẫn
            Image img = imageIcon.getImage().getScaledInstance(lblAvata.getWidth(), lblAvata.getHeight(), Image.SCALE_SMOOTH);  //set kích thước cho chuẩn
            lblAvata.setIcon(new ImageIcon(img));
            File file = new File(filePath);
            fileName = file.getName();
            System.out.println("fileName:" + fileName);
            //JOptionPane.showMessageDialog(this, "Ảnh đã được chọn: " + filePath);
        }
    }//GEN-LAST:event_btnAvataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(FrmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FrmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmNhanVien().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FrmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public Component getJpannelNV() {
        return jPanel1;
    }    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableNhanVien;
    private javax.swing.JButton btnAvata;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemm;
    private javax.swing.JButton btnTim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxChucVu;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private com.toedter.calendar.JDateChooser dcsNgayVaoLam;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel2;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private JLabel lblAvata;
    private JLabel lblChucVu;
    private JLabel lblHoTen;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    //SAO May ban code la ghe
    private void hienThiDanhSachNhanVien(List<NhanVien> danhSach) {
        DefaultTableModel model = (DefaultTableModel) TableNhanVien.getModel();
        model.setRowCount(0); // Xóa tất cả các hàng

        // Duyệt qua danh sách và thêm từng nhân viên vào bảng
        for (NhanVien nv : danhSach) {
            Object[] rowData = {
                nv.getMaNhanVien(),
                nv.getTenNV(),
                nv.getSoDT(),
                nv.getTrangThai(),
                nv.getCCCD(),
                nv.getDiaChi(),
                nv.getNgayVaoLam(),
                nv.getChucVu(),
                nv.getAvata()
            };
            model.addRow(rowData);
        }

    }

    private String phatSinhMaNVTuDong() throws Exception {
        // Vô hiệu hóa việc chỉnh sửa mã nhân viên
        txtMaNhanVien.setEditable(false);
        txtMaNhanVien.setEnabled(false);

        // Tạo đối tượng DAO_NhanVien để lấy thông tin nhân viên
        nv_dao = new DAO_NhanVien();
        int soLuongNhanVien = nv_dao.getSoLuongNhanVien();

        // Lấy danh sách nhân viên
        List<NhanVien> danhSachNhanVien = nv_dao.findAll();

        // Sinh mã nhân viên mới dựa trên số lượng hiện có
        String maNhanVienMoi;

        // Sinh mã nhân viên mới với 2 định dạng: NV001, NV002, ...
        if (soLuongNhanVien < 9) {
            maNhanVienMoi = "NV00" + (soLuongNhanVien + 1);
        } else {
            maNhanVienMoi = "NV0" + (soLuongNhanVien + 1);
        }

        // Kiểm tra xem mã đã tồn tại trong danh sách nhân viên chưa
        boolean maTonTai = false;

        for (NhanVien nv : danhSachNhanVien) {
            if (nv.getMaNhanVien().equalsIgnoreCase(maNhanVienMoi)) {
                maTonTai = true;
                break;
            }
        }

        // Nếu mã đã tồn tại, tăng số thứ tự để tránh trùng lặp
        while (maTonTai) {
            if (soLuongNhanVien < 9) {
                maNhanVienMoi = "NV00" + (soLuongNhanVien + 2);  // Sinh mã tiếp theo
            } else {
                maNhanVienMoi = "NV0" + (soLuongNhanVien + 2);  // Sinh mã tiếp theo
            }

            // Kiểm tra lại xem mã vừa tạo có bị trùng không
            maTonTai = false;
            for (NhanVien nv : danhSachNhanVien) {
                if (nv.getMaNhanVien().equalsIgnoreCase(maNhanVienMoi)) {
                    maTonTai = true;
                    break;
                }
            }
        }

        // Gán mã nhân viên mới vào textfield (hoặc trả về)
        return maNhanVienMoi;
    }

    private boolean checkData() throws Exception {
        String maNV = txtMaNhanVien.getText().trim();
        String tenNV = txtTenNV.getText().trim();
        String soDT = txtSDT.getText().trim();
        String trangThai = (String) cbxTrangThai.getSelectedItem(); // Giả sử bạn có một JComboBox cho trạng thái
        String cccd = txtCMND.getText().trim();
        String diaChi = txtDiaChi.getText().trim();
        Date ngayVaoLam = dcsNgayVaoLam.getDate(); // Giả sử bạn có một DateChooser cho ngày vào làm
        System.out.println("Ngay vao lam:" + ngayVaoLam);
        // Kiểm tra mã nhân viên
        if (!(maNV.length() > 0)) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên không được để trống");
            txtMaNhanVien.requestFocus();
            return false;
        }

        // Kiểm tra tên nhân viên
        if (!(tenNV.length() > 0)) {
            JOptionPane.showMessageDialog(this, "Tên không được để trống");
            txtTenNV.requestFocus();
            return false;
        }
        if (!tenNV.matches("^[A-Z][a-z]*(\\s[A-Z][a-z]*)*$")) {
            JOptionPane.showMessageDialog(this, "Tên phải bắt đầu bằng chữ hoa và theo sau là chữ thường, có thể có nhiều từ.");
            txtTenNV.requestFocus();
            return false;
        }

        if (!tenNV.matches("^[^0-9]+$")) {
            JOptionPane.showMessageDialog(this, "Tên không được có số");
            txtTenNV.requestFocus();
            return false;
        }

        if (!(txtSDT.getText().length() > 0 && txtSDT.getText().matches("^0\\d{9}$"))) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải gồm 10 số, bắt đầu bằng số 0.");
            txtSDT.requestFocus();
            return false;
        }

        // Kiểm tra chứng minh nhân dân
        if (!cccd.matches("^\\d{12}$")) {
            JOptionPane.showMessageDialog(this, "Căn cước công dân phải gồm 12 chữ số.");
            txtCMND.requestFocus();
            return false;
        }

        // Kiểm tra địa chỉ
        if (!(diaChi.length() > 0)) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống");
            txtDiaChi.requestFocus();
            return false;
        }

        // Kiểm tra ngày vào làm
        if (ngayVaoLam == null) {
            JOptionPane.showMessageDialog(this, "Ngày vào làm không được để trống");
            dcsNgayVaoLam.requestFocus();
            return false;
        } else {
            // Chuyển đổi ngayVaoLam từ Date sang LocalDate
            LocalDate ngayVaoLamLocalDate = ngayVaoLam.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            LocalDate today = LocalDate.now();
            if (ngayVaoLamLocalDate.isBefore(today)) {
                JOptionPane.showMessageDialog(this, "Ngày vào làm không được trước ngày hiện tại");
                dcsNgayVaoLam.requestFocus();
                return false;
            }
        }

        // Nếu tất cả kiểm tra đều thành công
        return true;
    }

// Phương thức để lấy tên ảnh từ JLabel
    private String getAvataFromLabel(JLabel label) {
        String imagePath = lblAvata.getIcon().toString();
        System.out.println("imagePath:" + imagePath);
        File file = new File(imagePath);
        System.out.println("file:" + file.getName());
        return file.getName();
    }

}
