/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entity.*;

import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.sql.Timestamp;
import java.util.List;
import DAO.DAO_TraVe;
import Database.ConnectDatabase;
import com.itextpdf.io.exceptions.IOException;

import java.text.DecimalFormat;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

import static GUI.InHoaDonTra.generateInvoicePdf;

/**
 *
 * @author ASUS
 */
public class TraVe_GUI extends JFrame {
    private NhanVien nhanvien;
    private JPanel traVePanel;
    private JTextField jTextField1;
    private JCheckBox jCheckBox2;

    public void setNhanViet(NhanVien nv){
        this.nhanvien = nv;
    }
    public NhanVien getNhanVien() {
        return nhanvien;
    }
    /**
     * Creates new form TraVe_GUI
     */
    public TraVe_GUI( NhanVien nv) {
         ConnectDatabase.getInstance().connect();
        initComponents();
        setNhanViet(nv) ;
        traVePanel = jPanelTraVe;
        System.out.println(nhanvien.getMaNhanVien());
        System.out.println(nv.getMaNhanVien());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        XacNhan = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblXacNhan = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTongPhi = new javax.swing.JLabel();
        lblTongVe1 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblTongTra = new javax.swing.JLabel();
        jPanelTraVe = new javax.swing.JPanel();
        jPanelChucNang = new javax.swing.JPanel();
        lblTraVe = new javax.swing.JLabel();
        jPanelTimKiem = new javax.swing.JPanel();
        txtMaVe = new javax.swing.JTextField();
        btnTimMaVe = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelTimTheoHoaDon = new javax.swing.JPanel();
        txtSDT = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        txtMaHD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTimHoaDon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableHienThi = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtTongVe = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTienPhi = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTienVe = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTienTra = new javax.swing.JTextField();
        btnTraVe = new javax.swing.JButton();

        XacNhan.setLocation(new java.awt.Point(350, 150));
        XacNhan.setSize(new java.awt.Dimension(800, 600));
        XacNhan.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                XacNhanComponentAdded(evt);
            }
        });
        XacNhan.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                XacNhanComponentHidden(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("Danh sách chọn trả");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addContainerGap())
        );

        tblXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblXacNhan.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Thông tin", "Tiền"
                }
        ));
        tblXacNhan.setEnabled(false);
        tblXacNhan.setFocusable(false);
        tblXacNhan.setRowHeight(100);
        jScrollPane1.setViewportView(tblXacNhan);

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Xác Nhận");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox1.setText("In Hóa Đơn ");

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox2.setText("Gửi Mail");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jCheckBox2)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jCheckBox1))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tổng vé: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tổng lệ phí");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Tổng Tiền Vé");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Tổng Tiền Trả");

        lblTongPhi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTongVe1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTongTra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTongTra.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(3, 3, 3)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTongVe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(lblTongPhi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(1, 1, 1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(32, 32, 32))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTongTra, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(lblTongVe1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addComponent(lblTongPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(lblTongTra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout XacNhanLayout = new javax.swing.GroupLayout(XacNhan.getContentPane());
        XacNhan.getContentPane().setLayout(XacNhanLayout);
        XacNhanLayout.setHorizontalGroup(
                XacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(XacNhanLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );
        XacNhanLayout.setVerticalGroup(
                XacNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(XacNhanLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTraVe.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTraVe.setText("Trả Vé");



        btnTimMaVe.setText("Tìm Theo Mã Vé");
        btnTimMaVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimMaVeActionPerformed(evt);
            }
        });

        jButton2.setText("QR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Số điện thoại");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Số Giấy Tờ");

        btnTimHoaDon.setText("Tìm Theo Hóa Đơn");
        btnTimHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimHoaDonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã Hóa Đơn");

        tableHienThi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tableHienThi.setForeground(new java.awt.Color(51, 51, 51));
        tableHienThi.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "STT", "Thông tin KH", "Thông tin  Vé", "Thành Tiền", "Phí Trả Vé", "Thông tin vé trả", "Chọn trả vé"
                }
        ));
        tableHienThi.setRowHeight(140);
        jScrollPane2.setViewportView(tableHienThi);
        if (tableHienThi.getColumnModel().getColumnCount() > 0) {
            tableHienThi.getColumnModel().getColumn(0).setResizable(false);
            tableHienThi.getColumnModel().getColumn(0).setPreferredWidth(1);
            tableHienThi.getColumnModel().getColumn(1).setMinWidth(200);
            tableHienThi.getColumnModel().getColumn(2).setMinWidth(200);
            tableHienThi.getColumnModel().getColumn(3).setPreferredWidth(50);
            tableHienThi.getColumnModel().getColumn(6).setMaxWidth(100);
        }

        btnReset.setBackground(new java.awt.Color(0, 255, 255));
        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnReset)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelTimTheoHoaDonLayout = new javax.swing.GroupLayout(jPanelTimTheoHoaDon);
        jPanelTimTheoHoaDon.setLayout(jPanelTimTheoHoaDonLayout);
        jPanelTimTheoHoaDonLayout.setHorizontalGroup(
                jPanelTimTheoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelTimTheoHoaDonLayout.createSequentialGroup()
                                .addGroup(jPanelTimTheoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTimTheoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSDT)
                                        .addComponent(txtCCCD)
                                        .addComponent(txtMaHD))
                                .addGap(18, 18, 18)
                                .addComponent(btnTimHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanelTimTheoHoaDonLayout.setVerticalGroup(
                jPanelTimTheoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTimTheoHoaDonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelTimTheoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelTimTheoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelTimTheoHoaDonLayout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addGroup(jPanelTimTheoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnTimHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanelTimTheoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCCCD)
                                        .addGroup(jPanelTimTheoHoaDonLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanelTimKiemLayout = new javax.swing.GroupLayout(jPanelTimKiem);
        jPanelTimKiem.setLayout(jPanelTimKiemLayout);
        jPanelTimKiemLayout.setHorizontalGroup(
                jPanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTimKiemLayout.createSequentialGroup()
                                .addGroup(jPanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelTimKiemLayout.createSequentialGroup()
                                                .addComponent(txtMaVe)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnTimMaVe)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanelTimTheoHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanelTimKiemLayout.setVerticalGroup(
                jPanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTimKiemLayout.createSequentialGroup()
                                .addGroup(jPanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnTimMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelTimTheoHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );

        jLabel17.setText("Tổng số Vé");

        txtTongVe.setEditable(false);
        txtTongVe.setText("0");
        txtTongVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongVeActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Tổng Phí");

        txtTienPhi.setEditable(false);
        txtTienPhi.setText("0");

        jLabel20.setText("Tổng Tiền Vé");

        txtTienVe.setEditable(false);
        txtTienVe.setText("0");
        txtTienVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addComponent(txtTongVe)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTienPhi)
                                                .addGap(18, 18, 18))
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addComponent(txtTienVe)
                                                .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtTongVe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtTienPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTienVe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Tổng Tiền Hoàn");

        txtTienTra.setEditable(false);
        txtTienTra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTienTra.setForeground(new java.awt.Color(255, 0, 51));
        txtTienTra.setText("0 ₫");
        txtTienTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienTraActionPerformed(evt);
            }
        });

        btnTraVe.setBackground(new java.awt.Color(0, 255, 255));
        btnTraVe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTraVe.setText("Trả Vé");
        btnTraVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelChucNangLayout = new javax.swing.GroupLayout(jPanelChucNang);
        jPanelChucNang.setLayout(jPanelChucNangLayout);
        jPanelChucNangLayout.setHorizontalGroup(
                jPanelChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelChucNangLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTraVe, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelChucNangLayout.createSequentialGroup()
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTienTra)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTraVe, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanelChucNangLayout.setVerticalGroup(
                jPanelChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelChucNangLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTraVe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtTienTra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnTraVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelTraVeLayout = new javax.swing.GroupLayout(jPanelTraVe);
        jPanelTraVe.setLayout(jPanelTraVeLayout);
        jPanelTraVeLayout.setHorizontalGroup(
                jPanelTraVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTraVeLayout.setVerticalGroup(
                jPanelTraVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTraVeLayout.createSequentialGroup()
                                .addComponent(jPanelChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelTraVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelTraVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void jButton2ActionPerformed(ActionEvent evt) {

            // Khởi tạo cửa sổ quét mã QR
            QR_Scan qrScan = new QR_Scan();

            // Thêm WindowListener để nhận kết quả từ QR_Scan khi đóng
            qrScan.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    // Lấy chuỗi kết quả từ mã QR và hiển thị trong txtHoTen
                    String qrResult = qrScan.getQrResult(); // Phương thức này cần được thêm trong lớp QR_Scan
                    if (qrResult != null && !qrResult.isEmpty()) {
                        txtMaVe.setText(qrResult); // Gán kết quả vào JTextField
                        btnTimMaVe.doClick(); // Tự động nhấn nút "Tìm Theo Mã Vé"
                    }
                }
            });
            qrScan.setVisible(true); // Hiển thị cửa sổ QR_Scan


    }                                        

    private void btnTimHoaDonActionPerformed(ActionEvent evt) {
        btnReset.doClick();
        String sdt = txtSDT.getText().trim();
        String maHD = txtMaHD.getText().trim();
        String cccd = txtCCCD.getText().trim();
        DAO_TraVe dao = new DAO_TraVe();
        if (maHD.isEmpty() || cccd.isEmpty() || sdt.isEmpty()) {
                     JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin: Mã HD, CCCD, SĐT.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    return;
           }

        
        List<VeTau> veTauList = dao.getVeTauByMaHDAndCCCDAndSDT(maHD, cccd, sdt);
         DefaultTableModel model = (DefaultTableModel) tableHienThi.getModel();
         model.setRowCount(0);
         
         
         if (veTauList.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
         for (VeTau veTau : veTauList) {
           VeTau ve = dao.getVeByMaVe(veTau.getMaVe());
            KhachHang kh = dao.getTenVaCCCDKhachHangByMaVe(veTau.getMaVe());
            LocalDate ngayKhoiHanh = ve.getLichTrinhTau().getNgayDi();
            LocalTime gioKhoiHanh = ve.getLichTrinhTau().getGioDi();
            LocalDateTime ngayKhoiHanhDateTime = ngayKhoiHanh.atTime(gioKhoiHanh);
            LocalDateTime currentTime = LocalDateTime.now();
            long hoursBetween = ChronoUnit.HOURS.between(currentTime, ngayKhoiHanhDateTime);
            double phiTraVe = 0.0;
            double giaVe = ve.getGiaVe();
            if (hoursBetween < 4) {
                phiTraVe = 0.0;
            } else if (hoursBetween >= 4 && hoursBetween < 24) {
                phiTraVe = giaVe * 0.2;
            } else {
                phiTraVe = giaVe * 0.1;
            }
            
            // Thông tin vé
            String hoTen = ve.getTenKhachHang();
            String doiTuong = ve.getDoiTuong();
            String giayTo = ve.getGiayTo();
            String tenTau = ve.getLichTrinhTau().getTau().getTenTau();
            String ngayDi = ve.getNgayDi().toString();
            String gioDi = ve.getLichTrinhTau().getGioDi().toString();
            int toa = ve.getChoNgoi().getToaTau().getThuTu();
            String soCho = ve.getChoNgoi().getTenCho();
            String loaiGhe = ve.getChoNgoi().getLoaiCho().getTenLoai();
            String ma = ve.getMaVe();
            double thanhTien = dao.getThanhTienByMaVe(ma);
            String tenNguoiDat = kh.getTenKhachHang();
            String giaToNguoiDat = kh.getCCCD();
            String trangThai = ve.getTrangThai();
            boolean tinhTien=true;
             boolean cb=true;
             if(hoursBetween<4){
                 trangThai="Quá hạn đổi";
                 tinhTien=false;
                 cb=false;
             }else if(trangThai.equals("Đã Trả")){

                 tinhTien=false;
                 cb=false;
             }
            model.addRow(new Object[]{
                    model.getRowCount() + 1, // Số thứ tự
                    "Họ Tên KH: " + hoTen + "\n" + doiTuong + "\n" + "Giấy tờ: " + giayTo + "\n" + "Người đặt: " + tenNguoiDat + "\n" + "Giấy tờ Người Đặt: " + giaToNguoiDat,
                    tenTau + " " + ngayDi + " " + gioDi + "\n" + "Toa: " + toa + " Ghế: " + soCho + "\n" + loaiGhe + "\n" + veTau.getMaVe(),
                    thanhTien,
                    phiTraVe,
                    trangThai,
                    cb  // Nút "Xóa" vào cột cuối
                });
            tableHienThi.setModel(model);
   
        // Cấu hình chiều cao của hàng và cột để hiển thị nhiều dòng
        tableHienThi.getColumnModel().getColumn(1).setCellRenderer(new MultiLineCellRenderer());
        tableHienThi.getColumnModel().getColumn(2).setCellRenderer(new MultiLineCellRenderer());
        tableHienThi.getColumnModel().getColumn(6).setCellRenderer(new CustomRenderer());
        tableHienThi.getColumnModel().getColumn(6).setCellEditor(new CustomEditor());
             if(tinhTien) TinhToan(model.getRowCount()-1,true );
    }   
    }                                            

    private void txtSDTActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }                                      

    private void btnTimMaVeActionPerformed(ActionEvent evt) {
      
    // Giả sử bạn đã có maVe từ người dùng nhập vào:
    ConnectDatabase.getInstance().connect();
    String maVe = txtMaVe.getText().trim();
    DAO_TraVe dao = new DAO_TraVe();

    // Gọi phương thức để lấy dữ liệu từ cơ sở dữ liệu hoặc đối tượng
    VeTau ve = dao.getVeByMaVe(maVe);
    KhachHang kh = dao.getTenVaCCCDKhachHangByMaVe(maVe);

    // Đảm bảo bạn đã thiết lập TableModel cho JTable
    DefaultTableModel model = (DefaultTableModel) tableHienThi.getModel();
   
    // Kiểm tra nếu mã vé đã tồn tại trong bảng
    boolean isMaVeExist = false;
    boolean isNguoiDatExist = true;
    
    for (int i = 0; i < model.getRowCount(); i++) {
         String rowContent = (String) model.getValueAt(i, 2); // Lấy nội dung từ cột mã vé (cột thứ 3)
         String[] parts = rowContent.split("\n");
         String rowContent2 = (String) model.getValueAt(i, 1);
          String[] parts2 = rowContent2.split("\n");
        String existingMaVe = parts[parts.length - 1].trim();
        String existingNguoiDat = parts2[parts2.length - 1].trim(); // Giả sử mã hóa đơn nằm ở phần đầu dòng
        
        if (existingMaVe.equals(maVe)) {
            isMaVeExist = true;
            break;
        }else if(!existingNguoiDat.endsWith(kh.getCCCD())){
            isNguoiDatExist = false;
            break;
        }
    }
   
    // Nếu mã vé đã tồn tại, thông báo cho người dùng
    if (isMaVeExist) {
        JOptionPane.showMessageDialog(this, "Mã vé đã tồn tại trong bảng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return; // Dừng việc thêm vé mới vào bảng
    }else if(!isNguoiDatExist){
        JOptionPane.showMessageDialog(this, "Vé trong 1 lần hủy phải cùng 1 người đặt", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return; // Dừng việc thêm vé mới vào bảng
    }

    // Nếu mã vé chưa tồn tại, tiếp tục thêm vé vào bảng
    LocalDate ngayKhoiHanh = ve.getLichTrinhTau().getNgayDi();
    LocalTime gioKhoiHanh = ve.getLichTrinhTau().getGioDi();
    LocalDateTime ngayKhoiHanhDateTime = ngayKhoiHanh.atTime(gioKhoiHanh);
    LocalDateTime currentTime = LocalDateTime.now();
    long hoursBetween = ChronoUnit.HOURS.between(currentTime, ngayKhoiHanhDateTime);
    double phiTraVe = 0.0;
    double giaVe = ve.getGiaVe();

    if (hoursBetween < 4) {
        phiTraVe = 0.0;
    } else if (hoursBetween >= 4 && hoursBetween < 24) {
        phiTraVe = giaVe * 0.2;
    } else {
        phiTraVe = giaVe * 0.1;
    }

    // Thông tin vé
    String hoTen = ve.getTenKhachHang();
    String doiTuong = ve.getDoiTuong();
    String giayTo = ve.getGiayTo();
    String tenTau = ve.getLichTrinhTau().getTau().getTenTau();
    String ngayDi = ve.getNgayDi().toString();
    String gioDi = ve.getLichTrinhTau().getGioDi().toString();
    int toa = ve.getChoNgoi().getToaTau().getThuTu();
    String soCho = ve.getChoNgoi().getTenCho();
    String loaiGhe = ve.getChoNgoi().getLoaiCho().getTenLoai();
    String ma = ve.getMaVe();
    double thanhTien = dao.getThanhTienByMaVe(ma);
    String tenNguoiDat = kh.getTenKhachHang();
    String giaToNguoiDat = kh.getCCCD();
    String trangThai = ve.getTrangThai();
    boolean tinhTien=true;
    boolean cb=true;
    if(hoursBetween<4){
        trangThai="Quá hạn đổi";
        tinhTien=false;
        cb=false;
    }else if(trangThai.equals("Đã Trả")){

            tinhTien=false;
            cb=false;
        }

    // Thêm dòng vào bảng
    model.addRow(new Object[]{
        model.getRowCount() + 1, // Số thứ tự
        "Họ Tên KH: " + hoTen + "\n" + doiTuong + "\n" + "Giấy tờ: " + giayTo + "\n" + "Người đặt: " + tenNguoiDat + "\n" + "Giấy tờ Người Đặt: " + giaToNguoiDat,
        tenTau + " " + ngayDi + " " + gioDi + "\n" + "Toa: " + toa + " Ghế: " + soCho + "\n" + loaiGhe + "\n" + maVe,
        thanhTien,
        phiTraVe,
        trangThai,
            cb  // Nút "Xóa" vào cột cuối
    });
    
    // Cập nhật lại bảng
    tableHienThi.setModel(model);
   
    // Cấu hình chiều cao của hàng và cột để hiển thị nhiều dòng
    tableHienThi.getColumnModel().getColumn(1).setCellRenderer(new MultiLineCellRenderer());
    tableHienThi.getColumnModel().getColumn(2).setCellRenderer(new MultiLineCellRenderer());
    tableHienThi.getColumnModel().getColumn(6).setCellRenderer(new CustomRenderer());
    tableHienThi.getColumnModel().getColumn(6).setCellEditor(new CustomEditor());
     if(tinhTien) TinhToan(model.getRowCount()-1,true );
    
    }                                          

    private void btnTraVeActionPerformed(ActionEvent evt) {
        // Lấy tổng số dòng trong bảng
DAO_TraVe dao = new DAO_TraVe();
DefaultTableModel model = (DefaultTableModel) tableHienThi.getModel();
int rowCount = model.getRowCount();

// Kiểm tra xem có vé nào được chọn không
boolean hasNewTicket = false;

for (int row = 0; row < rowCount; row++) {
    // Kiểm tra cột trạng thái của vé (cột cuối cùng)
    Boolean isSelected = (Boolean) model.getValueAt(row, 6); // Cột cuối cùng (trạng thái)
    if (isSelected != null && isSelected) {
        hasNewTicket = true; // Nếu có vé mới được chọn
        break; // Dừng vòng lặp vì đã tìm thấy vé mới
    }
}

// Kiểm tra nếu có vé mới, mở modal
if (hasNewTicket) {
    // Tạo danh sách các vé hợp lệ để trả
    DefaultTableModel model1 = (DefaultTableModel) tblXacNhan.getModel();
    model1.setRowCount(0);
    List<Object[]> veTauList = new ArrayList<>();

    for (int row = 0; row < rowCount; row++) {
        Boolean isSelected = (Boolean) model.getValueAt(row, 6);
        if (isSelected != null && isSelected) {
            // Lấy dữ liệu từ các cột khác
            String thongTinVe = (String) model.getValueAt(row, 2);

            // Trích xuất thông tin mã vé từ cột 2 (thông tin vé)
            String[] thongTinParts = thongTinVe.split("\n");
            String maVe = thongTinParts[thongTinParts.length - 1].trim(); // Mã vé là phần cuối cùng
            System.out.println(maVe);

            // Lấy thông tin vé từ DAO
            VeTau ve = dao.getVeByMaVe(maVe);
            String hoTen = ve.getTenKhachHang();
            String giayTo = ve.getGiayTo();
            String tenTau = ve.getLichTrinhTau().getTau().getTenTau();
            String soCho = ve.getChoNgoi().getTenCho();
            int toa = ve.getChoNgoi().getToaTau().getThuTu();
            double thanhTien = dao.getThanhTienByMaVe(maVe);
            Double phiTraVe = (Double) model.getValueAt(row, 4);
            String Tuyen =dao.getTenTuyenByMaVe(maVe);
            // Thêm dòng mới vào bảng xác nhận
            model1.addRow(new Object[]{
                "Tuyến:"+Tuyen+"\n"+"Họ Tên KH: " + hoTen + "\n" + "Tau: " + tenTau + " Toa: " + toa + " Số chỗ:" + soCho + "\n" + "Giấy tờ: " + giayTo,
                "Tiền Vé: " + thanhTien + "\n" + "Lệ Phí Trả Vé: " + phiTraVe + "\n" + "Tiền Trả: " + (thanhTien - phiTraVe)
            });
        }
        tblXacNhan.getColumnModel().getColumn(0).setCellRenderer(new MultiLineCellRenderer());
        tblXacNhan.getColumnModel().getColumn(1).setCellRenderer(new MultiLineCellRenderer());
    }

    // Cập nhật các giá trị tổng cộng
    lblTongPhi.setText(txtTienPhi.getText());
    lblTongVe1.setText(txtTongVe.getText());
    lblTongTien.setText(txtTienVe.getText());
    lblTongTra.setText(txtTienTra.getText());

    // Mở modal nếu có vé mới
    XacNhan.setModal(true); // Đảm bảo cửa sổ XacNhan là modal
    XacNhan.setVisible(true); // Hiển thị cửa sổ xác nhận
} else {
    // Nếu không có vé mới, có thể thông báo cho người dùng hoặc không làm gì cả
    JOptionPane.showMessageDialog(null, "Không có vé mới để xác nhận!");
}

    }                                        

    private void txtTongVeActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }                                         

    private void txtTienTraActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }                                          

    private void btnResetActionPerformed(ActionEvent evt) {
        NhanVien nv = getNhanVien();
        System.out.println("Mã nhân viên: " + nv.getMaNhanVien());
         // Lấy DefaultTableModel của bảng
    DefaultTableModel model = (DefaultTableModel) tableHienThi.getModel();
    
    // Xóa tất cả các dòng trong bảng
    model.setRowCount(0);

    // (Nếu cần) Cập nhật lại bảng hoặc làm gì đó sau khi reset bảng
    // Ví dụ: Nếu bạn muốn cập nhật lại chiều cao hàng hoặc cài đặt lại một số thuộc tính, bạn có thể làm ở đây.
    tableHienThi.setModel(model);
        txtTongVe.setText("0");
         txtTienPhi.setText(String.valueOf(0));
         txtTienVe.setText(String.valueOf(0));
         txtTienTra.setText(String.valueOf(0));
    // Thông báo cho người dùng
   
    }                                        

    private void XacNhanComponentHidden(ComponentEvent evt) {
        // TODO add your handling code here:
    }                                       

    private void XacNhanComponentAdded(ContainerEvent evt) {
        // TODO add your handling code here:
    }                                      

    private void txtTienVeActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }                                         

    private void jButton1ActionPerformed(ActionEvent evt) {
       XacNhan.setVisible(false);
    }                                        

    private void jButton3ActionPerformed(ActionEvent evt) {
        DAO_TraVe dao = new DAO_TraVe();

        DefaultTableModel model = (DefaultTableModel) tableHienThi.getModel();
        int rowCount = model.getRowCount();
        List<Object[]> veTauList = new ArrayList<>();
        String nhanVien = nhanvien.getMaNhanVien() ;
        String maHD = null;
        double[] tienGoc = new double[10];
        String[] tau = new String[10];
        for (int row = 0; row < rowCount; row++) {
            Boolean isSelected = (Boolean) model.getValueAt(row, 6);
            if (isSelected != null && isSelected) {
                // Lấy dữ liệu từ các cột khác
                String thongTinVe = (String) model.getValueAt(row, 2);

                // Trích xuất thông tin mã vé từ cột 2 (thông tin vé)
                String[] thongTinParts = thongTinVe.split("\n");
                String maVe = thongTinParts[thongTinParts.length - 1].trim(); // Mã vé là phần cuối cùng
                System.out.println(maVe);

                // Lấy thông tin vé từ DAO
                VeTau ve = dao.getVeByMaVe(maVe);
                KhachHang kh = dao.getTenVaCCCDKhachHangByMaVe(maVe);
                String hoTen = ve.getTenKhachHang();
                String giayTo = ve.getGiayTo();
                String tenTau = ve.getLichTrinhTau().getTau().getTenTau();
                String soCho = ve.getChoNgoi().getTenCho();
                int toa = ve.getChoNgoi().getToaTau().getThuTu();
                double thanhTien = dao.getThanhTienByMaVe(maVe);
                double phiTraVe = (double) model.getValueAt(row, 4);
                String Tuyen = dao.getTenTuyenByMaVe(maVe);
                String maNguoiDat=kh.getMaKhachHang();
                String tenNguoiDat = kh.getTenKhachHang();
                String giaToNguoiDat = kh.getCCCD();
                tienGoc[row]=thanhTien;
                tau[row] =tenTau;

                boolean isUpdated = dao.updateTrangThaiVe(maVe);
                if (isUpdated) {
                    System.out.println("Trạng thái vé đã được cập nhật thành 'Đã trả'.");

                    // Tính tổng tiền của tất cả vé trả
                    // Tạo hóa đơn mới và lấy mã hóa đơn

                    String tongTienTra = txtTienTra.getText();// Tổng tiền trả từ textbox
                    DecimalFormat decimalFormat = new DecimalFormat("#,###.##");
                    tongTienTra = tongTienTra.replace(",", "");
                    Number number = null;
                    try {
                        number = decimalFormat.parse(tongTienTra);
                    } catch (ParseException e) {
                        throw new RuntimeException(e);
                    }
                    float tongTien = number.floatValue();
                    // Thêm hóa đơn trả vé vào cơ sở dữ liệu
                    System.out.println("Mã người đặt: "+maNguoiDat);
                    System.out.println("Mã nhân viên: "+nhanVien);
                    System.out.println("Tổng tiền: "+tongTien);
                   // Thêm hóa đơn

                    if (maHD != null) {
                        System.out.println("Hóa đơn trả vé đã được tạo: " + maHD);
                    }else {
                        System.out.println("có mã rồi không tạo nữa: " + maHD);
                        maHD = dao.addHoaDon(maNguoiDat, nhanVien, (0-tongTien),new Timestamp(System.currentTimeMillis()));
                    }
                    // Thêm chi tiết hóa đơn cho từng vé đã chọn
                    int addchitiet=dao.addChiTietHoaDon(maVe,maHD,1,0,(float) (0.0-(thanhTien)),"0");
                    System.out.println("Chi tiết hóa đơn đã được thêm: " + maVe+maHD+"thanh tien"+(thanhTien));

                } else {
                    System.out.println("Lỗi khi cập nhật trạng thái vé.");
                }
            }
                String TongtienTra=txtTienTra.getText();

        }
        if (jCheckBox1.isSelected()) {
            HoaDon hoaDon = new HoaDon();
            hoaDon = dao.getHoaDonByMa(maHD);
            hoaDon = dao.getHoaDonByMa(maHD);
            KhachHang khachHang = new KhachHang();
            khachHang = dao.getKhachHangByMaKH(hoaDon.getKhachHang().getMaKhachHang());
            List<VeTau> ve = new ArrayList<>();
            ve = dao.getVeTauByMaHD(maHD);
            List<ChiTietHoaDon> chiTietHoaDonList = new ArrayList<>();
            chiTietHoaDonList = dao.getChiTietHoaDonByMaHD(maHD);
            generateInvoicePdf(hoaDon, khachHang, chiTietHoaDonList, ve, nhanVien, tienGoc, tau);
            String fileName = "hoadonTra.pdf";
            try {
                // Tạo đối tượng File từ tên file
                File pdfFile = new File(fileName);
                if (pdfFile.exists()) {
                    // Sử dụng Desktop để mở file PDF
                    Desktop.getDesktop().open(pdfFile);
                } else {
                    JOptionPane.showMessageDialog(null, "Không tìm thấy file PDF.");
                }
            } catch (IOException | java.io.IOException e1) {
                JOptionPane.showMessageDialog(null, "Không thể mở file PDF: " + e1.getMessage());
            }

        }
        if (jCheckBox2.isSelected()) {
            // Kiểm tra xem email trong jTextField1 có hợp lệ không
            String email = jTextField1.getText().trim();
            if (email.isEmpty() || !isValidEmail(email)) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập email hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return; // Dừng việc tiếp tục nếu email không hợp lệ
            }

            // Lấy các thông tin cần thiết từ DAO
            HoaDon hoaDon = dao.getHoaDonByMa(maHD);
            KhachHang khachHang = dao.getKhachHangByMaKH(hoaDon.getKhachHang().getMaKhachHang());
            List<VeTau> ve = dao.getVeTauByMaHD(maHD);
            List<ChiTietHoaDon> chiTietHoaDonList = dao.getChiTietHoaDonByMaHD(maHD);

            // Gọi phương thức gửi email với nội dung hóa đơn trả vé
            EmailSender.generateTraVe(hoaDon, khachHang, chiTietHoaDonList, ve, tienGoc, tau, email, "Hóa đơn trả vé tàu");
        }
        btnReset.doClick();
        XacNhan.setVisible(false);
    }
    private boolean isValidEmail(String email) {
        // Biểu thức chính quy kiểm tra email hợp lệ
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        return email.matches(emailRegex);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraVe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraVe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraVe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraVe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraVe_GUI(new NhanVien()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private JDialog XacNhan;
    private JButton btnReset;
    private JButton btnTimHoaDon;
    private JButton btnTimMaVe;
    private JButton btnTraVe;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JCheckBox jCheckBox1;
    private JLabel jLabel1;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JPanel jPanel1;
    private JPanel jPanel10;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanelChucNang;
    private JPanel jPanelTimKiem;
    private JPanel jPanelTimTheoHoaDon;
    private JPanel jPanelTraVe;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JLabel lblTongPhi;
    private JLabel lblTongTien;
    private JLabel lblTongTra;
    private JLabel lblTongVe1;
    private JLabel lblTraVe;
    private JTable tableHienThi;
    private JTable tblXacNhan;
    private JTextField txtCCCD;
    private JTextField txtMaHD;
    private JTextField txtMaVe;
    private JTextField txtSDT;
    private JTextField txtTienPhi;
    private JTextField txtTienTra;
    private JTextField txtTienVe;
    private JTextField txtTongVe;
    // End of variables declaration                   

    private static class MultiLineCellRenderer extends JTextArea implements TableCellRenderer {

        public MultiLineCellRenderer() {
            setLineWrap(true);
            setWrapStyleWord(true);
            setOpaque(true);
             setBorder(BorderFactory.createEmptyBorder());
        }
        @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
         setFont(new Font("Roboto", Font.PLAIN, 18)); 
         
        setText(value == null ? "" : value.toString());
        if (isSelected) {
            setBackground(table.getSelectionBackground());
            setForeground(table.getSelectionForeground());
        } else {
            setBackground(table.getBackground());
            setForeground(table.getForeground());
        }
        return this;
    }
    }
    
    
    
    class CustomRenderer extends DefaultTableCellRenderer {
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        // Lấy giá trị trạng thái từ model
        String trangThai = table.getModel().getValueAt(row, 5).toString(); // Cột trạng thái
        if (trangThai.equals("Đã Trả")) {
            // Trả về một JLabel rỗng nếu trạng thái không phải "Đã thanh toán"
            return new JLabel("");
        }
        // Nếu trạng thái là "Đã thanh toán", hiển thị checkbox
        JCheckBox checkBox = new JCheckBox();
        checkBox.setSelected(value != null && (boolean) value);
        return checkBox;
    }
}

// Sử dụng editor để ngăn chỉnh sửa checkbox nếu trạng thái không phù hợp
class CustomEditor extends DefaultCellEditor {
     private boolean lastState = false;
    public CustomEditor() {
        super(new JCheckBox());
        
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
        // Lấy giá trị trạng thái từ cột (giả sử cột trạng thái là cột thứ 6)
        String trangThai = table.getModel().getValueAt(row, 5).toString(); // Cột trạng thái (index 5)
        String rowContent = table.getModel().getValueAt(row, 2).toString();
        
          // Lấy nội dung từ cột mã vé (cột thứ 3)
     
            JCheckBox checkBox = (JCheckBox) super.getTableCellEditorComponent(table, value, isSelected, row, column);
        if (trangThai.equals("Đã Trả")) {
            checkBox.setEnabled(false); // Vô hiệu hóa checkbox
        } else {
            checkBox.setEnabled(true); // Cho phép chỉnh sửa checkbox nếu trạng thái là "Đã thanh toán"
        }

        if (checkBox.getItemListeners().length == 0) {
        // Đăng ký ItemListener chỉ một lần
        checkBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                // Kiểm tra xem trạng thái checkbox có thay đổi hay không
                boolean currentState = checkBox.isSelected(); // Lấy trạng thái hiện tại của checkbox

                if (currentState != lastState) { // Chỉ xử lý khi trạng thái thay đổi
                    if (e.getStateChange() == ItemEvent.SELECTED) {
                        // Xử lý khi checkbox được chọn
                    } else {
                        // Xử lý khi checkbox không được chọn
                    }
                    lastState = currentState; // Cập nhật trạng thái cuối cùng
                }
               
                TinhToan(row, lastState);
            }
        });
    }

    return checkBox;
    }
    
    }
    public void TinhToan(int row,boolean check){
      try {
    // Lấy giá trị từ JTextField
    String txtTongVeValue = txtTongVe.getText();  // Ví dụ: "10"
    String txtTienPhiValue = txtTienPhi.getText(); // Ví dụ: "50.000"
    String txtTienVeValue = txtTienVe.getText();   // Ví dụ: "200.000"
    String txtTienTraValue = txtTienTra.getText(); // Ví dụ: "150.000"

    // Tạo DecimalFormat để định dạng tiền tệ
    DecimalFormat decimalFormat = new DecimalFormat("#,###.##");
    decimalFormat.setParseBigDecimal(true);  // Cho phép phân tích giá trị tiền tệ lớn

    // Làm sạch các ký tự không hợp lệ (dấu phẩy, dấu cách, dấu ₫)
    txtTienPhiValue = txtTienPhiValue.replaceAll("[^\\d.,]", "");
    txtTienVeValue = txtTienVeValue.replaceAll("[^\\d.,]", "");
    txtTienTraValue = txtTienTraValue.replaceAll("[^\\d.,]", "");

    // Kiểm tra nếu giá trị là "0" hoặc rỗng
    if (txtTienPhiValue.equals("0") || txtTienPhiValue.isEmpty()) {
        txtTienPhiValue = "0"; // Gán giá trị mặc định nếu không có giá trị
    }
    if (txtTienVeValue.equals("0") || txtTienVeValue.isEmpty()) {
        txtTienVeValue = "0"; // Gán giá trị mặc định nếu không có giá trị
    }
    if (txtTienTraValue.equals("0") || txtTienTraValue.isEmpty()) {
        txtTienTraValue = "0"; // Gán giá trị mặc định nếu không có giá trị
    }

    // Chuyển đổi giá trị từ JTextField sang các kiểu số
    int tongVe = Integer.parseInt(txtTongVeValue);  // Không cần xử lý tiền tệ vì số lượng là nguyên
    double tongPhi = decimalFormat.parse(txtTienPhiValue).doubleValue();  // Xử lý tiền tệ
    double tongTienVe = decimalFormat.parse(txtTienVeValue).doubleValue(); // Xử lý tiền tệ
    double tongTra = decimalFormat.parse(txtTienTraValue).doubleValue(); // Xử lý tiền tệ

    // Kiểm tra điều kiện và cập nhật giá trị
    if (check == true) {
        tongVe++;
        String phi = tableHienThi.getModel().getValueAt(row, 4).toString();
        String tienVe = tableHienThi.getModel().getValueAt(row, 3).toString();
        tongPhi += Double.parseDouble(phi);
        tongTienVe += Double.parseDouble(tienVe);
    } else {
        tongVe--;
        String phi = tableHienThi.getModel().getValueAt(row, 4).toString();
        String tienVe = tableHienThi.getModel().getValueAt(row, 3).toString();
        tongPhi -= Double.parseDouble(phi);
        tongTienVe -= Double.parseDouble(tienVe);
    }

    // Định dạng và hiển thị lại các giá trị vào JTextField
    txtTongVe.setText(String.valueOf(tongVe)); // Nếu `tongVe` là số lượng, không cần định dạng tiền tệ

    // Định dạng tiền phí và tiền vé
    txtTienPhi.setText(decimalFormat.format(tongPhi)); // Định dạng tiền phí
    txtTienVe.setText(decimalFormat.format(tongTienVe)); // Định dạng tiền vé

    // Tính tiền trả và định dạng
    double tienTra = tongTienVe - tongPhi;
    txtTienTra.setText(decimalFormat.format(tienTra)); // Hiển thị tiền trả đã định dạng

    } catch (ParseException e) {
    e.printStackTrace(); // Nếu có lỗi khi phân tích giá trị tiền tệ
    } catch (NumberFormatException e) {
    e.printStackTrace(); // Nếu có lỗi khi chuyển đổi kiểu dữ liệu số
    }



    }
    public Component getTrave() {

        return traVePanel;
    }
}

